name: Frontend Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        id: image_tag
        run: |
          # 리눅스 시간대를 서울로 설정 후 포맷팅
          sudo timedatectl set-timezone Asia/Seoul
          echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 
            ${{ secrets.DOCKERHUB_USERNAME }}/leafy-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/leafy-frontend:{TAG}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/deploy
            cd /home/ubuntu/deploy
            echo "TAG=${{ env.TAG }}" >> .env
            sudo docker compose pull frontend
            sudo docker compose up -d --force-recreate frontend
            sudo docker image prune -f
